repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=120"]
        exclude: app/core/security/__init__.py|alembic/

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
    -   id: pylint
        args: ["--max-line-length=120",
               "--disable=too-few-public-methods,missing-docstring,invalid-name,redefined-outer-name,logging-format-interpolation,too-many-ancestors",
               "--ignored-modules=dependency_injector, pydantic",
               "--max-args=7"]
        # disabled plugins: pylint.extensions.mccabe
        exclude: tests|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/|doc/|alembic/
        language: system

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
