version: '3.6'

services:

  api:
    image: api:lastest
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8000:8000
    volumes:
      - ./app:/app/app
    working_dir: /app/app
